gText_Birch_Welcome::
	.string "Hello, child.\p"
	.string "Welcome to the world of POKéMON.\p"
	.string "My name is ARCHER.\n"
	.string "I am Kanto's POKéMON Professor.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as POKéMON.\p"
	.string "If you have the money, you too can\n"
	.string "obtain one.\p"
	.string "That is what we in the ROCKET\n"
	.string "organization are here to provide.\p"
	.string "Our purview extends to more than\n"
	.string "just POKéMON, of course.\p"
	.string "Technology, pharmaceuticals,\n"
	.string "raw materials, information...\p"
	.string "If it can be bought, ROCKET sells\n"
	.string "it.\p"
	.string "That is what we do.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?\p"
	.string "$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "I see.\n"
	.string "And what is your name?$"

gText_Birch_SoItsPlayer::
	.string "Your name is {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, I see.\p"
	.string "You're {PLAYER}{KUN} who's moving to\n"
	.string "VIRIDIAN CITY.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Well then, are you prepared?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "I hope our collaboration will be\n"
	.string "mutually beneficial.\p"
	.string "I'll be expecting you later.\n"
	.string "Come see me in the POKéMON LAB.\p"
	.string "$"
